In [5]:
#numpy
import numpy as np

In [7]:
n1= np.array([10,20,30])


In [9]:
n1

array([10, 20, 30])

In [15]:
type(n1)

numpy.ndarray

In [28]:
n2=np.array([[1,2,3,4,6],[5,6,7,8,9]])

In [30]:
n2

array([[1, 2, 3, 4, 6],
       [5, 6, 7, 8, 9]])

In [32]:
n1=np.zeros((1,2))

In [34]:
n1

array([[0., 0.]])

In [36]:
n2=np.zeros((3,3))
n2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
n3=np.full((2,2),10)
n3

array([[10, 10],
       [10, 10]])

In [49]:
n4=np.arange(10,20)
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
n5=np.arange(10,51,5)
n5

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [53]:
# 5 random numbers 
n6=np.random.randint(1,200,5)
n6

array([ 19, 119, 138,  79, 156])

In [55]:
n7=np.array([[1,2,3],[5,6,7]])
n7.shape

(2, 3)

In [57]:
n7.shape=(3,2)
n7

array([[1, 2],
       [3, 5],
       [6, 7]])

In [19]:
n1= np.array([10,20,30,70])
n2= np.array([40,50,60,70])

np.vstack((n1,n2))


array([[10, 20, 30, 70],
       [40, 50, 60, 70]])

In [13]:

np.hstack((n1,n2))



array([10, 20, 30, 40, 50, 60])

In [17]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [23]:
np.intersect1d(n1,n2)

array([70])

In [27]:
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [29]:
np.setdiff1d(n2,n1)

array([40, 50, 60])

In [31]:
#addintion
n1=np.array([20,40])
n2=np.array([30,40])

In [35]:
np.sum((n1,n2))

130

In [37]:
np.sum((n1,n2),axis= 0)

array([50, 80])

In [39]:
np.sum((n1,n2),axis=1)

array([60, 70])

In [47]:
n7=np.array([[1,2,3],[5,6,7],[8,7,6]])
n7

array([[1, 2, 3],
       [5, 6, 7],
       [8, 7, 6]])

In [45]:
n7[:,1]

array([2, 6, 7])

In [49]:
n7.transpose()

array([[1, 5, 8],
       [2, 6, 7],
       [3, 7, 6]])

In [51]:
n8=np.array([[10,20,30],[50,60,70],[80,70,60]])
n8

array([[10, 20, 30],
       [50, 60, 70],
       [80, 70, 60]])

In [53]:
n7.dot(n8)

array([[ 350,  350,  350],
       [ 910,  950,  990],
       [ 910, 1000, 1090]])

In [55]:
np.save("my_numpy",n8)

In [57]:
n1=np.load("my_numpy.npy")
n1

array([[10, 20, 30],
       [50, 60, 70],
       [80, 70, 60]])

In [3]:
import numpy as np

x = np.random.normal(170, 10, 250)

print(x)

[149.45540618 165.18585841 169.15341551 169.32481314 169.78403246
 171.44966316 173.15466367 170.88682251 174.77250946 168.23567721
 170.89667491 175.32090213 164.14047634 176.28989244 165.8729183
 167.56883898 179.41428428 177.98463042 155.50374148 170.63400092
 178.16863601 159.68991044 157.92045272 186.50183141 178.17440188
 164.77847712 169.54800939 176.37047742 156.65960617 184.7605867
 187.5252951  173.42259965 163.43414929 174.3050986  176.63243506
 178.59979728 170.16341795 162.33483017 176.94670594 176.85610555
 180.36804657 167.23894097 159.88808958 187.78132056 175.36691748
 170.54876362 155.4902483  179.66579606 172.19199715 162.27699813
 178.50651828 185.7428739  173.43404011 175.3672936  166.87024545
 170.26325672 149.43351152 182.01020675 178.80412359 167.21702003
 171.09941987 178.57776803 158.51531553 168.59711883 181.19199204
 161.01878039 165.88060547 187.8743068  161.7011281  180.58249086
 161.84563398 166.85953037 175.282896   175.78511758 178.31514605
 186.6518136

In [5]:
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [7]:
import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


In [5]:
import numpy as np
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]
out

array([1, 2])

In [11]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[2,1],[1,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 1],
       [1, 2]])